### ISSUE TITLE
Pythia is not working anymore

### ISSUE THREAD

**Issue by fstrub95** [Cloud-CV/VQA#7]
Hi folks, 

First of all, thank you for your great website that show several core results visually grounded language learning. 

I am often using it to show the evolution of VQA over the years, and it seems that the website (http://vqa.cloudcv.org/) has been partially working for a few months: the pythia model does not work (nothing is displayed while submitting questions) while HieCoAtt perfectly works.

Kind regards, 
Florian

**Comment by iamzchi** [comment]
i dont know if it was fixed but pythia model can operate and give answers normally in my browser.

**Comment by RishabhJain2018** [comment]
It is fixed and working now! Closing it since it is resolved.
